print("Welcome to the tip calculator!")
amt=float(input("What was the total bill?"))
tip_percent=int(input("How much Percent tip would you like to give? 10,12, or 15?=>"))
people=int(input("How many people to split the bill?"))
percent=float((amt*tip_percent)/100)
each_amt=float(amt/people)
each_percent=float(percent/people)
each_total=float(each_amt+each_percent)
new_each_total=round(each_total,2)
print(f"Each person should pay: {new_each_total}")